# Sidebar navigation

- label: เกี่ยวกับเรา
  link: /
- label: Cloud
  items:
    - label: Azure App Service
      link: /cloud/azure-app-service
    - label: Azure SQL database
      link: /cloud/azure-sql-database

