name: Build and deploy Gatsby to Azure App Service Container

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 12.x # Set the Node.js version to use.
  DOCKER_IMAGE_NAME: ${{ secrets.LOGIN_SERVER }}/my-company-wiki:${{ github.sha }}

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest source code from ${{ github.sha }} commit.
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Create an authenticated emails file from a GitHub Secrets value.
        uses: "finnp/create-file-action@master" # https://github.com/finnp/create-file-action
        env:
          FILE_NAME: authenticated-emails.txt
          FILE_BASE64: ${{ secrets.AUTHENTICATED_EMAILS }}

      # logging purpose only
      # - name: Output authenticated-emails file.
      #   run: |
      #     cat authenticated-emails.txt

      - uses: azure/docker-login@v1 # https://github.com/Azure/docker-login
        with:
          login-server: ${{ secrets.LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push a new image to Azure Container Registry
        run: |
          docker build . --tag ${{ env.DOCKER_IMAGE_NAME }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_CONTAINER_PUBLISH_PROFILE }}
          images: ${{ env.DOCKER_IMAGE_NAME }}
