name: Build and deploy Gatsby to Azure App Service container

on:
  push:
    branches:
      - main

env:
  # Docker image name looks like "your-username/my-company-wiki:0fd5f6b9a71eb9dcf5f30c70f6e1b9b77dfadfb5"
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:${{ github.sha }}

jobs:
  build_and_deploy_job:
    # Link
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest source code from ${{ github.sha }} commit.
        uses: actions/checkout@v2 # https://github.com/actions/checkout

      - name: Create an authenticated emails file from a GitHub Secrets value.
        uses: finnp/create-file-action@master # https://github.com/finnp/create-file-action
        env:
          FILE_NAME: authenticated-emails.txt
          FILE_BASE64: ${{ secrets.AUTHENTICATED_EMAILS }}

      # logging purpose only
      # - name: Output authenticated-emails file.
      #   run: |
      #     cat authenticated-emails.txt

      - name: Login to Docker Hub.
        uses: docker/login-action@v1 # https://github.com/docker/login-action/releases
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push a new image to Docker Hub
        run: |
          docker build . --tag ${{ env.DOCKER_IMAGE_NAME }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}

      - name: Deploy a Docker image to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_CONTAINER_PUBLISH_PROFILE }}
          images: ${{ env.DOCKER_IMAGE_NAME }}
